### ISSUE TITLE
ensure monitorPipe goroutines are joined before terminating a pipeline

### ISSUE THREAD

**Issue by kaniini** [chainguard-dev/melange#109]
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x48 pc=0x4ed93e]

goroutine 9 [running]:
log.(*Logger).Printf(0xc000405f20?, {0xbb39ce?, 0x2e?}, {0xc000405ef8?, 0x0?, 0x0?})
        log/log.go:205 +0x1e
chainguard.dev/melange/pkg/build.(*Pipeline).monitorPipe(0xc000342100, {0xccca80?, 0xc000012140})
        chainguard.dev/melange/pkg/build/pipeline.go:200 +0x1cf
created by chainguard.dev/melange/pkg/build.(*Pipeline).evalRun
        chainguard.dev/melange/pkg/build/pipeline.go:232 +0x357
```

**Comment by kaniini** [comment]
I took care of this :)
