### ISSUE TITLE
`PATH` is not set in `build --debug`

### ISSUE THREAD

**Issue by smoser** [chainguard-dev/melange#1359]
I've bumped into a lot of different times when running `melange build --debug` but never really understood it.
Now I understand whats going on.  PATH is not actually set in the environment, it gets set by the shell builtin, but not exported.

Here is an example.

```yaml
$ cat test-me.yaml 
package:
  name: test-me
  version: 1.0
  epoch: 0

environment:
  contents:
    packages:
      - busybox
      - python3

pipeline:
  - runs: |
      echo this is building something
      cat >my.py <<"EOF"
      import os, sys
      print("inside %s: PATH=%s" % (sys.executable, os.environ["PATH"]))
      EOF
      python3 my.py
      exit 1
```

```bash
$ melange build --debug test-me.yaml \
   --repository-append=https://packages.wolfi.dev/os \
   --keyring-append=https://packages.wolfi.dev/os/wolfi-signing.rsa.pub \
   --arch=x86_64 --debug --interactive
2024/07/09 16:03:19 INFO ImgRef = /tmp/melange-guest-350654200
2024/07/09 16:03:19 WARN + export 'PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'
2024/07/09 16:03:19 WARN + export 'HISTFILE=~/.ash_history'
2024/07/09 16:03:19 WARN + '[' -d /home/build ]
2024/07/09 16:03:19 WARN + cd /home/build
2024/07/09 16:03:19 WARN + echo this is building something
2024/07/09 16:03:19 WARN + cat
2024/07/09 16:03:19 INFO this is building something
2024/07/09 16:03:19 WARN + python3 my.py
2024/07/09 16:03:19 INFO inside /usr/bin/python3: PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
2024/07/09 16:03:19 WARN + exit 1
...
## above is output, here is interactive shell, run the same 'my.py'
$ python3 ./my.py 
Traceback (most recent call last):
  File "/home/build/./my.py", line 2, in <module>
    print("inside %s: PATH=%s" % (sys.executable, os.environ["PATH"]))
                                                  ~~~~~~~~~~^^^^^^^^
  File "<frozen os>", line 714, in __getitem__
KeyError: 'PATH'

```

```
$ melange version
  __  __   _____   _          _      _   _    ____   _____
 |  \/  | | ____| | |        / \    | \ | |  / ___| | ____|
 | |\/| | |  _|   | |       / _ \   |  \| | | |  _  |  _|
 | |  | | | |___  | |___   / ___ \  | |\  | | |_| | | |___
 |_|  |_| |_____| |_____| /_/   \_\ |_| \_|  \____| |_____|
melange

GitVersion:    devel
GitCommit:     3cf5782215a0e9c4073c9dd6dfd69e4e410be438
GitTreeState:  dirty
BuildDate:     2024-06-19T21:14:46
GoVersion:     go1.22.3
Compiler:      gc
Platform:      linux/amd64
```

**Comment by smoser** [comment]
It *feels* to me like the right way to fix this is to use `pipelineRunner.Config.Environment` rather than 'export PATH' (and other environment variables) in the shell.
